"""
Environment Setup Script

Creates a .env file with PostgreSQL configuration based on user inputs.
Corresponds to the DataConfig class in rpd_core/data_cfg.py
"""

from os import environ
from pathlib import Path


def get_input(prompt: str, default: str = None) -> str:
    """Get user input with optional default value."""
    if default:
        user_input = input(f"{prompt} [{default}]: ").strip()
        return user_input if user_input else default
    else:
        user_input = input(f"{prompt}: ").strip()
        while not user_input:
            print("This field is required.")
            user_input = input(f"{prompt}: ").strip()
        return user_input


def main():
    print("=" * 60)
    print("PostgreSQL Environment Configuration Setup")
    print("=" * 60)
    print("\nThis script will create a .env file with database credentials.")
    print("Press Enter to accept default values shown in brackets.\n")

    # Check if .env already exists
    env_file = Path(".env")
    if env_file.exists():
        overwrite = (
            input(".env file already exists. Overwrite? (y/N): ").strip().lower()
        )
        if overwrite != "y":
            print("Setup cancelled.")
            return

    # Gather configuration values
    config = {
        "PG_HOST": get_input("PostgreSQL Host", default="localhost"),
        "PG_PORT": get_input("PostgreSQL Port", default="5432"),
        "PG_DB": get_input("Database Name", default="rpd_hub"),
        "PG_USER": get_input("Database User", default=environ.get("USER")),
        "PG_PASS": get_input("Database Password", default="***"),
    }

    # Create .env file content
    env_content = "# PostgreSQL Database Configuration\n"
    env_content += "# Generated by env_setup.py\n\n"

    for key, value in config.items():
        if key == "PG_PASS" and value == "***":
            value = ""
        env_content += f"{key}={value}\n"

    # Write to .env file
    env_file.write_text(env_content)

    print("\n" + "=" * 60)
    print(f"✓ Configuration saved to {env_file.absolute()}")
    print("=" * 60)
    print("\nConfiguration summary:")
    for key, value in config.items():
        # Mask password for display
        display_value = "*" * len(value) if key == "PG_PASS" else value
        print(f"  {key}: {display_value}")

    print("\nYou can now use this configuration in your application.")
    print("To modify these settings, either:")
    print("  1. Run this script again")
    print("  2. Edit .env file directly")


if __name__ == "__main__":
    main()
